# fly.toml app configuration file generated for expense-tracker-app-backend on 2023-11-04T12:07:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "expense-tracker-app-backend"
primary_region = "arn"

[build]
  image = "danisaghy/expense-tracker-app-backend:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  
#  [[services.http_checks]]
#  interval = 10000
#  timeout = 2000
#  method = "get"
#  path = "/healthcheck"
#  protocol = "http"
#  tls_skip_verify = false
#  [services.http_checks.headers]

[env]
  NODE_ENV = "production"
  URL = "https://expense-tracker-app-backend.fly.dev:"
  PORT = "8080"
  DATABASE_SSL = "true"